version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=quitter_app.extensions:app
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:////app/instance/database.db
      - SECRET_KEY=itsasecret
    volumes:
      - ./quitter_app:/app/quitter_app
      - ./instance:/app/instance
    command: flask run --host=0.0.0.0